# Generated by Django 6.0.5 on 2026-05-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theatre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "screen_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("imax", "IMAX"),
                            ("dolby", "Dolby"),
                            ("3d", "3D"),
                        ],
                        default="standard",
                        max_length=30,
                    ),
                ),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theatres",
                        to="cinema.cinema",
                    ),
                ),
            ],
            options={
                "ordering": ["cinema__name", "name"],
                "unique_together": {("cinema", "name")},
            },
        ),
    ]
