# Generated by Django 6.0.5 on 2026-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
