# Generated by Django 6.0.5 on 2026-05-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration_mins", models.PositiveIntegerField()),
                ("genre", models.CharField(max_length=120)),
                ("rating", models.CharField(max_length=20)),
                ("poster_url", models.URLField(blank=True)),
                ("release_date", models.DateField()),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-release_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("seats_available", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="movies.movie",
                    ),
                ),
                (
                    "theatre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="cinema.theatre",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
