# Generated by Django 6.0.5 on 2026-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
